//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTravel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MehsulOzellik
    {
        public int MehsulID { get; set; }
        public int OzellikTipID { get; set; }
        public int OzellikDeyerID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Mehsul Mehsul { get; set; }
        public virtual OzellikDeyer OzellikDeyer { get; set; }
        public virtual OzellikTip OzellikTip { get; set; }
    }
}
