//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTravel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mehsul
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mehsul()
        {
            this.MehsulOzellik = new HashSet<MehsulOzellik>();
            this.Photos = new HashSet<Photos>();
            this.Satis = new HashSet<Satis>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public decimal Qiymeti { get; set; }
        public Nullable<short> Endirimi { get; set; }
        public System.DateTime Tarixi { get; set; }
        public Nullable<int> KategoriyaID { get; set; }
        public string Haqqinda { get; set; }
        public string Aciqlama { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Kategoriya Kategoriya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MehsulOzellik> MehsulOzellik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photos> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satis> Satis { get; set; }
    }
}
