//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTravel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messaj
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
        public string MessageText { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public bool IsActive { get; set; }
    }
}
