//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTravel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzellikDeyer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OzellikDeyer()
        {
            this.MehsulOzellik = new HashSet<MehsulOzellik>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public Nullable<int> OzellikTipID { get; set; }
        public string Aciqlama { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MehsulOzellik> MehsulOzellik { get; set; }
        public virtual OzellikTip OzellikTip { get; set; }
    }
}
