//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTravel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public int Id { get; set; }
        public Nullable<int> MehsulID { get; set; }
        public Nullable<int> KategoriyaID { get; set; }
        public string BoyukYol { get; set; }
        public string OrtaYol { get; set; }
        public string KicikYol { get; set; }
        public Nullable<bool> Main { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Kategoriya Kategoriya { get; set; }
        public virtual Mehsul Mehsul { get; set; }
    }
}
